### ISSUE TITLE
section-headings always use heavy font weight

### ISSUE THREAD

**Issue by mnquintana** [braver/isotope-ui#13]
![screenshot 2015-01-27 08 48 17](https://cloud.githubusercontent.com/assets/823545/5919416/748f7882-a601-11e4-9e4b-c9d11d8259ef.png)

It would be cool if the headings' font weight was proportional to the user-selected font weight – ie. just heavier than the UI font weight, but not always the same heavy weight bold.

**Comment by braver** [comment]
Yes, I think you're right... that's a lot of work though... :wink:

**Comment by braver** [comment]
I believe https://github.com/braver/isotope-ui/commit/84b9b1a8e089246fd4c95771146d05f3f6c2b9fc solves this. I feel like I could express it in less lines of CSS, but it works. Basically, in @font-face I match "medium" to "thin" and "semibold" to "light", instead of simply using bold. When available of course. Looks better. I'll test it, think about refactoring the whole weights thing, and release somewhere the coming days.
Thanks for reporting!
