### ISSUE TITLE
1.3.0 dropped thicker tabs?

### ISSUE THREAD

**Issue by JoshStrobl** [braver/isotope-ui#21]
So after I installed the latest version I opted to read the Changelog. Apparently in 1.3 you landed thinner tabs, which I don't have a problem with, but the fact is you made it default AND dropped the option to disable the thinner tabs.

Seriously, what the fuck.  How can I get my thicker editor tabs back?

**Comment by braver** [comment]
Watch your tone dude. I'm spending a lot of my spare time on this and giving it to you for free. If you don't like the thing I gave to you for no cost at all, you can just take your f-words and go take a hike.

Just because I am a nice dude, I'm going to give you even more things you don't deserve, for free. Perhaps you'll take a hint, perhaps not. But I'm giving you the benefit of the doubt because there is a small chance you are actually a nice dude as well, but just unable to communicate well online.

There is, as for anything, an explanation.

All configuration options come with a maintenance costs. You just have to look at the commit log to see how much work I put into this theme. Improving, tweaking, keeping up with Atom updates, etc. I found that the old default and spacious layout didn't offer real benefits, and found myself switching to the compact layout even on my 24" display. Taking out this option made changing and testing the theme much easier. The core team has extensive plans to make configuring themes much easier to maintain, when that lands, Isotope is set up to take full advantage of that and offer loads of options. Until that time, I might take some options out, or add new ones in, who knows.

Again, it's just me, in my spare time, giving you this for free. No warranties, no promises, just my best effort.

You want it to be different? Fork it!
